import Head from "next/head";

const ProfilePage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div>
          profile view
        </div>
      </main>
    </>
  );
}

export default ProfilePage;
